version: "3.8"

services:
  phel_cli_skeleton:
    container_name: phel_cli_skeleton
    build:
      context: .
      dockerfile: build/Dockerfile
    hostname: php
    volumes:
      - .:/srv/phel-cli-skeleton:delegated
    command: ["/bin/bash"]
    tty: true
    stdin_open: true
